### ISSUE TITLE
Multiple tag serialization error

### ISSUE THREAD

**Issue by viggyfresh** [elos/x#20]
* See attached screenshot for the error - appears to be poorly serialized JSON
* Input query that causes this error:
    ```Javascript
    return fetch(`${hestiaHost}/query/`, {
        'method': 'post',
        'headers': headers(),
        'body': JSON.stringify({
            'kind': ELOS_KIND_TAG
        })
    }).then(...);
    ```
* Only an issue when you have multiple tags 😅 
![bad tag json](https://cloud.githubusercontent.com/assets/4701451/24596147/e9dee41a-17f1-11e7-9a28-7533fc0f49cb.png)

**Comment by nlandolfi** [comment]
The error resulted from a bug in adding commas between the tasks while unmarshalling them. Fixed in https://github.com/elos/x/pull/21.
